### ISSUE TITLE
wrn: cannot open resource

### ISSUE THREAD

**Issue by raphaeldore** [javiereguiluz/easybook#10]
Hello,

When I run a simple `./book publish 'test' print` I keep getting these errors:

```
wrn: cannot open resource (/home/dorer/Documents/EasyBook/app/Resources/Fonts/Neuton/Neuton-Regular.ttf)
wrn: cannot open resource (/home/dorer/Documents/EasyBook/app/Resources/Fonts/Neuton/Neuton-Bold.ttf)
wrn: cannot open resource (/home/dorer/Documents/EasyBook/app/Rssources/Fonts/Neuton/Neuton-Italic.ttf)
```

But the operation still works fine, it's just I don't think I am getting all the feature, since the chapter titles didn't look that great (or maybe it's just me). How can I solve this?

**Comment by larosa217** [comment]
I just downloaded this the other day and I'm experiencing the same issue on my Windows laptop (Win 8.1). As the original person said, the PDF still gets created, but I'd like to figure out how I can resolve these errors/warnings.
