### ISSUE TITLE
Alternative for PrinceXML

### ISSUE THREAD

**Issue by Purus** [javiereguiluz/easybook#132]
Is there any plan to use some open-source or low cost software for PDF conversion? PrinceXML is very much costly.. If I have to use it in my server, I have to pay my 6 months salary to get 1 server license.

The below one is open-source and widely used too.

http://code.google.com/p/wkhtmltopdf/

**Comment by sfermigier** [comment]
http://weasyprint.org/ (open source, Python)

**Comment by vbd** [comment]
http://wkhtmltopdf.org/

**Comment by holloway** [comment]
Found this thread in 2019... just fyi Google Puppeteer is how you do this now

https://github.com/GoogleChrome/puppeteer/blob/v1.12.2/docs/api.md#pagepdfoptions
