### ISSUE TITLE
The new easybook roadmap

### ISSUE THREAD

**Issue by javiereguiluz** [javiereguiluz/easybook#137]
After some months of very slow development, I can finally start again improving **easybook**. This is the planned roadmap for the coming months:
- **Short term**:
  - Add a true theme and plugin system
  - Regain the platinum medal on SensioLabsInsight ([ref](https://insight.sensiolabs.com/projects/34c47e7f-a523-4702-8310-ebec02a6a241/analyses/41))
  - Move the project from `javiereguiluz/*` to [easybook GitHub organization](https://github.com/easybook)
  - Release the 5.0 stable version.
- **Medium term**:
  - Achieve syntax/features parity with Leanpub (refs #138)
  - Work on some high quality themes
  - Work on some useful plugins
  - Replace the custom configuration resolver with the [OptionsResolver](http://symfony.com/doc/current/components/options_resolver.html) component from Symfony (refs #147)
  - Use all the latest Console component features (refs #149)
- **Long term**:
  - Work on HHVM compatibility
  - Consider alternatives for PrinceXML (refs #25 and #132)
  - Consider alternatives for PHP-Markdown library
  - Add support for reStructuredText as input format
  - Add support for HTML as input format

**Comment by Purus** [comment]
Hi,

Any thoughts or change in priority for alternatives on price-xml?
