### ISSUE TITLE
Composer install leads to "Class Pimple not found"

### ISSUE THREAD

**Issue by charlycoste** [javiereguiluz/easybook#156]
I tried to install easybook via composer and tried `./book -version`, but I got a

    PHP Fatal error:  Class 'Pimple' not found in /home/[...]/src/Easybook/DependencyInjection/Application.php on line 32

Using actual `dev-master` version of **Pimple** as dependency seams to leads to unfoundable classes.
It's maybe a temporary error from Pimple repository, but as the last stable version (4.8) of easybook is using `dev-master` for Pimple, installations from composer will be unusable!

Only the `dev-master` of **easybook** is ok because it's using the 1.1.1 version of Pimple. But this version is not the one that we get we using  `composer create-project easybook/easybook project_folder`

I see two solutions: 
- Releasing a new stable version with the same dependencies of the current `dev-master` version of  easybook
- Updating README file to inform users they need to use : `composer create-project easybook/easybook:dev-master project_folder` to get a working install.

**Comment by valueforvalue** [comment]
@charlycoste Thanks for the info on this saved me a bunch of time.

**Comment by javiereguiluz** [comment]
Fixed in the latest version, where Pimple has been updated to version 3.0. Besides, the new installation instructions of the project recommend only to use Composer.
