### ISSUE TITLE
Define a new syntax for image alignment

### ISSUE THREAD

**Issue by javiereguiluz** [javiereguiluz/easybook#49]
Markdown / Markdown Extra don't support image alignment:

```
![Alt text](image01.png)
```

This may be sufficient for webpages, but real-world books need to align images to the right/left/center. New syntax proposals:

```
![Alt text](:image01.png)
![Alt text](image01.png:)
![Alt text](:image01.png:)

![Alt text](_image01.png)
![Alt text](image01.png_)
![Alt text](_image01.png_)

![Alt text](image01.png)<-
![Alt text](image01.png)->
![Alt text](image01.png)<->

![Alt text](image01.png)(left)
![Alt text](image01.png)(right)
![Alt text](image01.png)(center)

![Alt text](image01.png){ align: left }
![Alt text](image01.png){ align: right }
![Alt text](image01.png){ align: center }
```

**Comment by fabiosalles** [comment]
I just tried to center image and it failed. Googling a bit I was able to get it to work following http://webdesign.about.com/od/beginningcss/a/aa012207.htm and adding 

  margin-left: auto;
  margin-right: auto;

To ".center img {" tag in ./easybook/app/Resources/Themes/Base/Html/Templates/css/images.css.twig. The whole tag ended up like this:

.center img {
    display: block;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
}

I would like to help by commiting this change but I am tooo noob for that, so here it is. I've done that on the 5.0-Dev (a git pull.)
